version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.1.3-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run

  action_server:
    image: rasa/rasa-sdk:latest
    ports:
      - "5055:5055"
    volumes:
      - actions:actions"